### PR TITLE
Fixes #16: Migrate to vitest

### LINKED ISSUE #16: Migrate to `vitest`
Can we consider replacing `jest` with `vitest`? There is no particular issue with jest but vitest is just faster :)

### PR DESCRIPTION
**Pull request by mkangoo**
Transition from `jest` to `vitest`

### CODE REVIEW

**Comment by mkangoo** [comment]
[Solving the problem with Husky when using Vitest](https://stackoverflow.com/questions/71672335/how-to-configure-husky-pre-push-hook-to-run-tests?newreg=a398c2c81c45409791907d54207e86bb)

**Comment by mkangoo** [comment]
@Ilanaya Please check me. Everything seems to be working and there are no conflicts

**Comment by mkangoo** [comment]
I added the ability to view code coverage by tests `npm run coverage`
image

**Comment by Ilanaya** [comment]
Yep, I didn't run tests but changes look good. BTW, did you like the feature of not importing 'describe', 'it' etc to the test files? If you do you can configure vitest to   do this for you

**Comment by mkangoo** [comment]
This is cool, I implemented it

**Pull request merged**
